### ISSUE TITLE
Outdated README

### ISSUE THREAD

**Issue by vmx** [multiformats/multicodec#133]
The current README is heavily outdated. You can see that there's several left-overs from earlier versions of the multiformats stuff (e.g. references to multistreams). The current README defines multicodec as being a data format/encoding like the other multiformats are. It's specified as `<codec-encoded-as-varint><data>`.

I went over the other multiformats (multiaddr, multihash, multibase, multistream-select, cid). There the term "multicodec" is used (if used) as being am identifier encoded as varint, hence just as `<codec-encoded-as-varint>` without the `<data>` piece.

I can see two ways moving forward. We could expand the multicodec format and use it also in other specs, or we drop the multicodec format and use just the codec table.

### Expanding the multicodec format

Currently the only case where we use `<codec-encoded-as-varint><data>` is within CIDs. To expand it to other specs it would need to change a bit to be useful. It could be `<codec-encoded-as-varint><data-length-as-varint><data>` with optionally just `<codec-encoded-as-varint><data>` if the codec specifies a fixed size (e.g. multiaddr when using ipv4).

That way multihash would just be a multicodec. Also the binary representation of multiaddr would just be a list of multicodecs.

### Dropping multiformat as format

We could also just remove the `<codec-encoded-as-varint><data>` part and define multicodec as just being a table of codecs which is used by the various multiformats.

If that's the plan I'd suggest renaming it to "multiformat codecs" and moving the table into the multiformats repo. Then removing the multicodec repository as it would be meaningless.

/cc @mikeal

**Comment by mikeal** [comment]
I hadn’t realized that `mulithash` wasn’t actually using multicodec, but it sort of makes sense given the history.

So, the way I would frame this is, do we plan on using multicodec in a future version of multihash? If the answer is **no** then I’d say that we drop it.

How solidified is multicodec as `<codec-varint><data>` only? How disruptive would allowing `<codec-varint><data-length><data>` be?

**Comment by Stebalien** [comment]
IMO, the issue is that we're overloading the term. There's still a place for self-describing data streams. That's really where the "<mc><data>" version of multicodec came from (first question: https://github.com/multiformats/multicodec/#faq).

For some history:

1. In the beginning, there was multicodec. Multicodec used _strings_.
2. Later, multistream was introduced. Multistream allowd for negotiating network streams using multicodec as defined in 1.
3. Then (or before?), multicodec-packed came about because strings are just way too big.
4. At some point, multicodec-packed got renamed to multicodec, multicodec got renamed to multistream, and multistream got renamed to multistream-select.
5. Finally, the multihash/multicodec/multibase tables were _merged_ and this all got a lot more confusing.
6. Multibase was unmerged.

> So, the way I would frame this is, do we plan on using multicodec in a future version of multihash? If the answer is no then I’d say that we drop it.

Almost certainly not. IIRC, the length was a deliberate decision.

**Comment by vmx** [comment]
> > So, the way I would frame this is, do we plan on using multicodec in a future version of multihash? If the answer is no then I’d say that we drop it.
> 
> Almost certainly not. IIRC, the length was a deliberate decision.

I don't think @mikeal point was about dropping the `length` in `multihash`, but using `<codec-varint><data-length><data>` as a definition for multicodec in case we want to use it as a definition of multihash.

**Comment by vmx** [comment]
> There's still a place for self-describing data streams. That's really where the `<mc><data>` version of multicodec came from.

I'm not sure if that needs a separate spec. It could be just a note in the repository that contains the multicodec table that you can use them not only in multihash or CIDs, but also to prefix your own data.
