### ISSUE TITLE
comparison with cbor

### ISSUE THREAD

**Issue by KrishnaPG** [multiformats/multicodec#148]
Trying to understand the difference between this and `cbor`. Looks like both use some pre-defined values to represent their content. Wondering what is the difference, and if there are any cost/performance pros/cons.

Not to mention, this multicodec also supports `cbor` as one of the types in the tables. That sounds like a double / duplicate content description (first one telling the rest of the content is 'cbor', and then 'cbor' telling that the rest of the content is, say `ip-address` or `url` or `binary` etc.). Not sure why would one want to use such duplicated representation, unnecessarily increasing the content length.

Would `cbor` be not equal to something like `multihash` rather ? wondering which one is more preferred for future-proof and storing content into DB.

**Comment by vmx** [comment]
Multicodec is just a prefix for your data. When you read the Multicodec first, you know how to process the subsequent data. So when you store binary data in your database, you could store it in any format you like (e.g. CBOR or MessagePack) and identify how it was stored by just readin the Multicodec.

Another good example of how Multicodec can be used is [CID](https://github.com/multiformats/cid/)s.


PS: There's currently #134 open, let me know if you find whether [that version of the README](https://github.com/multiformats/multicodec/blob/7446d91c70ad2815717df649c4d81965db42c6da/README.md) would be clearer.

**Comment by KrishnaPG** [comment]
Thank you @vmx 

I am trying to understand in what situations I would pick `multicodec` and in what situations I would be picking `cbor`.

Maybe someone can correct me, but my understanding from the notes and the above reply is: 

If I come across any serialized binary data, and I do not know what exactly the data contains, then I can use `multicodec` to safely deserialize it correctly, unlike `cbor` which expects me to have all the tags that may have been used inside it to be present with me.

Is that accurate? Are there any situations where I can **not** deserialize any `multicodec` encoded data that I receive (without having to know something about that data). That is, would it work with completely zero-knowledge about the coded data, 100% always?

**Comment by vmx** [comment]
> I am trying to understand in what situations I would pick `multicodec` and in what situations I would be picking `cbor`.

If CBOR is good enough, just use CBOR. If you want to have more flexibility to use any possible data, use Multicodec.

> That is, would it work with completely zero-knowledge about the coded data, 100% always?

If you come across any serialized binary data, you won't/can't know how to interpret this data, there's no way that you could know. It could be random data, it could be CBOR, it could be a video file. You need some indication.

That indication will come from the system you are building. One way, to support any data format would be Multicodec. But before you even look at the data, you would need to know/make sure that the binary data you are reading is actually Multicodec prefixed.

If CBOR is a good enough format for all your data, you can just make sure that all your data is actually CBOR and you are good (just as you made sure all your data is Multicodec prefixed).

**Comment by mikeal** [comment]
The use case is similar to the scheme in a URL. A domain name alone tells you where to connect on the internet and if you’re *only* ever going to use HTTP you don’t need a scheme, you would just always connect to port 80. But since we want to future-proof addresses for future protocol changes, we have a scheme, and now you know if someone wants a domain name over HTTP or HTTPS.

It’s the same thing here, you’re handed an “address” (a hash) for binary data. The hash is enough of an identifier to grab the data, but it’s not enough to know how to interpret it. If you only ever support CBOR then you just try to parse all data using CBOR, but if you want to future proof for other data types, or you just want to be able to link to blocks of raw binary data as well as CBOR, you’ll need to put something in the address that tells you how to interpret the data.

Hope that helps.

**Comment by KrishnaPG** [comment]
Thank you @mikeal . That is helpful.

The follow-up question then is: given that `cbor` is also a schema + data representation, much like `multicodec`, wondering what was the reason for creating a new spec (multicodec), instead of chosing to use `cbor`. Any drawbacks with `cbor` (or for that matter any of its equivalents, such as msgpack etc.)? They all pack the (data + how to read the data) in a similar way.

I am just trying to understand the whole scenario of where each of these tools fit exactly, and any such background information would greatly help the understanding. 

What I am seeing is, on the decoding side the `multi-codec`, `cbor`, `msgpack` etc. they all are equivalent (unless I am missing some point, learning of which is the whole goal of this thread). They all know how exactly to decode the data. 

For CIDs I am already using multi-codec and its peers. But the problem oftentimes I faced is, you have to encode the data first (eg. buffer -> base64 / hex / base58 etc.) and then multi-code it. And choosing which exact coding method you want to use (e.g. hex, base64 etc.), is upto you. Whereas with likes of `cbor` it seems you just give the data, and you get back "coded" representation already. No need to worry about choosing between base64, hex, base58 etc. (trust me, making that choice is not easy and I have come across long threads where people argue over hex vs base58 vs base52, and what not).

Multi-codec nicely solves the problem of telling which codec _was_ used for an already coded data. But it does not help with "choosing" the right codec for any given _uncoded_ data. Given that as a user I still have to decide which codec to use (to encode it), this is where the likes of `cbor` deviate from the `multi-codec`. I guess multi-codec does not specify the input codec, while the likes of `cbor` decide it for the user. 

In one sense, `multi-codec` offers the freedom of chosing your own input codec - which is both a bless and curse. Bless if you want to share the coded data with others. Curse, if the data is just for internal storage and you do not know which codec is best for your purpose + you have to write additional encoding code.

Is this some valid line of thought? or Am I missing something?

**Comment by vmx** [comment]
@KrishnaPG Multicodec is just a table of numbers you can prefix your data with. You could then use [unsigned-varint](https://github.com/multiformats/unsigned-varint) to encode that prefix.

When your data has such a prefix, it's easy to determine what it is. Is is CBOR, msgpack or a Git Object?

Let's say you want to store a Git Object, which consists of the bytes `0x01, 0x02, 0x03`.

When you use Multicodec as a prefix of your binary data, you would varint encode that identifier and append the binary data. So the encoded data would be `0x78 0x01 0x02 0x03`. That's 4 bytes of payload. 

If you don't like varints, you could also use CBOR for it. You would probably encode it as a two element array, where the first element is the identifier what the binary data is about (you would probably use Multicodec for this, so that you don't need to introduce your own table) and the second one the actual data. Your encoded data would then look like [that](http://cbor.me/?diag=[120,%20h%27010203%27]):

```
82           # array(2)
   18 78     # unsigned(120)
   43        # bytes(3)
      010203 # "\x01\x02\x03"
```

The total payload is 7 bytes.

In both examples you need some kind of table to indicate which data you're actually storing. That table is Multicodec.

**Comment by mikeal** [comment]
@KrishnaPG the goal of multicodec is to create as small a representation as possible. Remember that, since these are addresses, they end up being embedded as links in other data structures and passed around in applications, so every byte counts.

If you created a CBOR based wrapper for this meta information the resulting cbor object would be significantly larger than a `CID`, and that would result in much larger blocks containing links and incredibly large (possibly too large) URL parameters and the like.

**Comment by KrishnaPG** [comment]
@mikeal the size of the output being larger for CBOR makes sense. Thank you - that is helpful.
