### ISSUE TITLE
Way to encode random IDs (UUID)

### ISSUE THREAD

**Issue by vladimir-vg** [multiformats/multicodec#169]
Hello everyone!

I use binary keys sole purpose of which is to be random and not clash with other keys. These keys are guaranteed to hold no meaning for human or machine, just an ID. I also use multihash keys in same namespace.

I would like to use these random keys and be sure that it will not clash with multihash keys.

How can I encode a random binary id in multicodec? This would make everything work together nicely.

**Comment by vladimir-vg** [comment]
UUID is just an example, not necessarily this format.

**Comment by ribasushi** [comment]
Random ID ( uuid or otherwise ) encoded as a legitimate CID:
`\x01` `\x55` `\x00` `varint length of id` `id itself`

https://github.com/multiformats/multicodec/blob/master/table.csv#L2

**Comment by vladimir-vg** [comment]
Thanks!

`\x01` `\x55` `\x00` `varint length of id` `id itself`

I want to be sure I understand it correctly.
 * `\x01` points out the version of CID
 * `\x55` points out to raw format https://github.com/multiformats/multicodec/blob/master/table.csv#L35
 * `\x00` points out to identity hash

Correct?

**Comment by Stebalien** [comment]
Yes.

**Comment by ribasushi** [comment]
@vladimir-vg glad it worked for you! Please close the ticket if your request has been resolved 👍

**Comment by rvagg** [comment]
It might make sense to have a UUID multicodec, they're already somewhat self describing (I think you can determine which one of the ~5 versions a UUID is just by reading it) but there may be a valid use for being able to say "this thing is a UUID". You'd usually be wanting to do such a thing in a case where the "thing" could be something else too, so a class of such "things" where UUID is just one of them.
I don't think multicodec is going to lend any affordances for presenting a "compact" form, however, that's not really what multicodec does, it's just a way of prefixing something to identify what that something is and you still need the _something_. UUIDs in CIDs might give you some interesting possibilities, but you're really in the realm of identity CIDs as outlined in this thread since you're not presenting a "content identifier".
