### ISSUE TITLE
Multicodec trailing slash discrependency

### ISSUE THREAD

**Issue by Kubuxu** [multiformats/multicodec#21]
go-multicodec uses `/json` as an example, spec says `/json/`.

@dignifiedquire could you take a look at what js-multicodec is using?

**Comment by dignifiedquire** [comment]
@Kubuxu I'm not seeing any handling of `/`es in multiformats/js-multicodec.

**Comment by diasdavid** [comment]
@Kubuxu please see: https://github.com/multiformats/multicodec/tree/spec/update

We use the `/` on multistream - https://github.com/multiformats/multistream

**Comment by Kubuxu** [comment]
@diasdavid the trailing `/`, examples in multistream's readme say otherwise.

I don't seem to understand the updated spec, are we moving away from the path based format?

If yes, is there reasoning behind it? For me it seems like paths like `/multiaddr/tcp` are better than just `tcp`.

**Comment by diasdavid** [comment]
We are not moving from a path based for the things like multihash, multiaddr, etc. The updated multicodec spec is just in fact, multicodec-packed, which defines the binary packed codes for each format so that other multiformats can use. See also: https://github.com/multiformats/multicodec/pull/16 (all the comments)

**Comment by Kubuxu** [comment]
commented in #16

**Comment by vmx** [comment]
This discussion is about an old version of multicodec and is no longer applicable.
