### ISSUE TITLE
Unicode characters

### ISSUE THREAD

**Issue by crackcomm** [multiformats/multicodec#64]
It would be funny and useful to have unicode characters table mapping unicode 📠 to protocols.

I am not sure how would we decide on certain protocols etc. but I am honestly interested in hearing your feedback on that idea.

**Comment by Stebalien** [comment]
Having unicode-based icons for protocols would be interesting but yeah, finding a good *unique* mapping would be rather difficult (if not impossible). Also, the fact that user's can't *type* these characters significantly reduces their utility (although they can still be used for display).

Instead of restricting ourselves to Unicode, we could also just create an icon set. That is, if someone volunteers to make one. Unfortunately, we'd lose the ability to display them in the terminal (well, most of them) if we did that.

**Comment by crackcomm** [comment]
I will close this for same reason as #63. Thank you @Stebalien for your engagement.
